version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: maginanime
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your-password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./maginanime.backup:/docker-entrypoint-initdb.d/maginanime.backup
    command: ["postgres", "-c", "max_connections=300"]


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres-data:
